spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dasom
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: lyi98549854
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  refresh-exp: 2592000000
  access-exp: 60000
  prefix: Bearer
  header: Authorization
  secret-key: 1MO+JNPjpeqNV/zS1Oz7D2Tirs0zo+PRY4hmpwnUigmlBjLi9Bc7b/KHTlmHyFLuX9s+UkilRMFJinKULR61jQ==